<header class="gt-top-menu xs-left">
  <img src="assets/img/gaintime.png" alt="" />
  <label class="menu-toggle">
    <svg viewBox="0 0 24 24">
      <path fill="#333" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z"></path>
    </svg>
  </label>
  <nav>
    <ul>
      <a href="."><li>Home</li></a>
      <a href="new-daily.php"><li class="active">Diário das Marias</li></a>
      <a href=""><li class="active">Próximos eventos</li></a>
      <a href=""><li class="active">Contatos</li></a>
      <a href=""><li class="active">Rede de apoio</li></a>
    </ul>
  </nav>
</header>