<header class="gt-top-menu xs-left">
  <img src="https://hackathon.startonapp.com/assets/img/Realiza%C3%A7%C3%A3o/rondamariadapenha.png" alt="" />
  <label class="menu-toggle">
    <svg viewBox="0 0 24 24">
      <path fill="#333" d="M3,6H21V8H3V6M3,11H21V13H3V11M3,16H21V18H3V16Z"></path>
    </svg>
  </label>
  <nav>
    <ul>
      <a href="." class="active"><li>Home</li></a>
      <a href="new-daily.php"><li class="active">Diário das Marias</li></a>
      <a href="events.php"><li class="active">Próximos eventos</li></a>
      <a href="contacts.php"><li class="active">Contatos</li></a>
      <a href=""><li class="active">Rede de apoio</li></a>
    </ul>
  </nav>
</header>
<script type="text/javascript" src="../vendors/gainTime-2.1.2/jss/gaintime.min.js"></script>
<script type="text/javascript" src="../../vendors/gainTime-2.1.2/js/gaintime.min.js"></script>