-- MySQL Script generated by MySQL Workbench
-- Sáb 03 Jun 2017 22:23:57 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema salvamaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salvamaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salvamaria` DEFAULT CHARACTER SET utf8 ;
USE `salvamaria` ;

-- -----------------------------------------------------
-- Table `salvamaria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`users` (
  `id` INT NOT NULL,
  `processo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL DEFAULT '',
  `complemento` VARCHAR(55) NULL,
  `endereco_visita` VARCHAR(100) NULL,
  `ponto_referencia` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `turno_visita` VARCHAR(45) NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `filhos` VARCHAR(45) NOT NULL,
  `filhos_com_agressor` VARCHAR(45) NOT NULL,
  `escolaridade` VARCHAR(45) NOT NULL,
  `etnia` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `religiao` VARCHAR(45) NOT NULL,
  `profissao` VARCHAR(45) NOT NULL,
  `trabalha` TINYINT(1) NOT NULL,
  `ultimo_emprego` VARCHAR(45) NOT NULL,
  `local_trabalho` VARCHAR(45) NOT NULL,
  `renda` VARCHAR(45) NOT NULL,
  `responsavel_sustento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `salvamaria`.`certidoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`certidoes` (
  `id` INT NOT NULL,
  `tipo` ENUM('FISCALIZACAO', 'RECUSA', 'RETORNO', 'TERMINO', 'NEGATIVA_ENDERECO') NOT NULL,
  `data` DATETIME NOT NULL,
  `testemunha` VARCHAR(100) NOT NULL,
  `depoimento_usuaria` MEDIUMTEXT NOT NULL,
  `depoimento_agressor` MEDIUMTEXT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_certidoes_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_certidoes_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `salvamaria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `salvamaria` ;

-- -----------------------------------------------------
-- Placeholder table for view `salvamaria`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `salvamaria`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salvamaria`.`view1`;
USE `salvamaria`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
